# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f291a7f5d64dad2e4686f252e888226"
name = "search-auto-dashboard"
handle = "search-auto-dashboard-2"
application_url = "https://yeast-ronald-entered-ranger.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "suspensionpro.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://yeast-ronald-entered-ranger.trycloudflare.com/auth/callback",
  "https://yeast-ronald-entered-ranger.trycloudflare.com/auth/shopify/callback",
  "https://yeast-ronald-entered-ranger.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
